import { db } from './index.js'
import { vars } from './schema.js'

// ============================================================================
// Unified VAR Dataset — Merged from VAR Directory (51) + M&A Engine (40)
// Overlapping companies keep Source 1 rich data + Source 2 M&A fields
// Source 2-only companies get generated baseline fields
// ============================================================================

const UNIFIED_VARS = [
  // -----------------------------------------------------------------------
  // 1. CDW Corporation — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "CDW Corporation",
    website: "cdw.com",
    hqCity: "Lincolnshire",
    hqState: "IL",
    annualRevenue: 21500,
    profit: 1050,
    employeeCount: 15100,
    ownershipType: "Public",
    strategicSpecialty: "Full-Stack IT Solutions",
    strategicFocus: "Multi-vendor IT procurement, cloud, security, and infrastructure solutions for enterprise, government, and education",
    topVendors: ["Microsoft", "Cisco", "Dell", "HP", "Lenovo", "VMware"],
    topCustomers: ["Federal Government", "K-12 Education", "Healthcare Systems"],
    yearFounded: 1984,
    description: "Largest US VAR by revenue. Multi-brand technology solutions provider serving business, government, education, and healthcare customers with end-to-end IT lifecycle services.",
    dataSources: ["var-directory"],
    confidenceScore: 0.95,
    growthRate: null as number | null,
    ebitdaMargin: null as number | null,
    customerSegment: null as string | null,
    specialties: null as string[] | null,
    latitude: 42.2025,
    longitude: -87.9539,
  },
  // -----------------------------------------------------------------------
  // 2. World Wide Technology (WWT) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "World Wide Technology (WWT)",
    website: "wwt.com",
    hqCity: "St. Louis",
    hqState: "MO",
    annualRevenue: 17000,
    profit: 850,
    employeeCount: 10000,
    ownershipType: "Private",
    strategicSpecialty: "Advanced Technology Center",
    strategicFocus: "Digital strategy, ATC lab environment, cloud, networking, and security solutions for Fortune 500 enterprises",
    topVendors: ["Cisco", "Dell", "HP", "NetApp", "Palo Alto Networks", "F5"],
    topCustomers: ["Fortune 500 Enterprises", "Federal Agencies", "Financial Services"],
    yearFounded: 1990,
    description: "Privately held technology solution provider and systems integrator known for its Advanced Technology Center (ATC), a virtual and physical lab for testing enterprise solutions at scale.",
    dataSources: ["var-directory"],
    confidenceScore: 0.9,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 38.627,
    longitude: -90.1994,
  },
  // -----------------------------------------------------------------------
  // 3. SHI International — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "SHI International",
    website: "shi.com",
    hqCity: "Somerset",
    hqState: "NJ",
    annualRevenue: 14000,
    profit: null,
    employeeCount: 6000,
    ownershipType: "Private",
    strategicSpecialty: "Software & Cloud Licensing",
    strategicFocus: "Software asset management, cloud migration, ITAM, and procurement optimization for global enterprises",
    topVendors: ["Microsoft", "Adobe", "VMware", "AWS", "Cisco", "Dell"],
    topCustomers: ["Fortune 500 Enterprises", "Public Sector", "Higher Education"],
    yearFounded: 1989,
    description: "One of the largest minority and woman-owned businesses in the US. Specializes in software licensing, cloud solutions, and IT asset management for enterprise and public sector clients.",
    dataSources: ["var-directory"],
    confidenceScore: 0.9,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 40.4974,
    longitude: -74.4888,
  },
  // -----------------------------------------------------------------------
  // 4. Insight Enterprises — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Insight Enterprises",
    website: "insight.com",
    hqCity: "Chandler",
    hqState: "AZ",
    annualRevenue: 9100,
    profit: 280,
    employeeCount: 13500,
    ownershipType: "Public",
    strategicSpecialty: "Solutions Integration",
    strategicFocus: "Cloud and data center transformation, connected workforce, digital innovation, and supply chain optimization",
    topVendors: ["Microsoft", "HP", "Dell", "Cisco", "AWS", "Google Cloud"],
    topCustomers: ["Enterprise", "Healthcare", "Government"],
    yearFounded: 1988,
    description: "Fortune 500 Solutions Integrator providing Intelligent Technology Solutions across cloud, data center, connected workforce, and supply chain optimization.",
    dataSources: ["var-directory"],
    confidenceScore: 0.95,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 33.3062,
    longitude: -111.8413,
  },
  // -----------------------------------------------------------------------
  // 5. Presidio — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Presidio",
    website: "presidio.com",
    hqCity: "New York",
    hqState: "NY",
    annualRevenue: 3500,
    profit: null,
    employeeCount: 3200,
    ownershipType: "PE",
    strategicSpecialty: "Digital Infrastructure",
    strategicFocus: "Network, security, cloud, and collaboration solutions with emphasis on digital transformation and managed services",
    topVendors: ["Cisco", "Palo Alto Networks", "Microsoft", "AWS", "Dell", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Financial Services", "Healthcare"],
    yearFounded: 2004,
    description: "PE-backed IT solutions provider focused on digital infrastructure, cloud, security, and lifecycle management. Known for deep Cisco expertise and managed services capabilities.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.85,
    growthRate: 12,
    ebitdaMargin: 11,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Cybersecurity", "Managed Services", "Networking"],
    latitude: 40.7128,
    longitude: -74.006,
  },
  // -----------------------------------------------------------------------
  // 6. Connection (PC Connection) — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Connection (PC Connection)",
    website: "connection.com",
    hqCity: "Merrimack",
    hqState: "NH",
    annualRevenue: 3300,
    profit: 105,
    employeeCount: 2700,
    ownershipType: "Public",
    strategicSpecialty: "IT Procurement",
    strategicFocus: "IT solutions for SMB, mid-market, and public sector with strong supply chain and configuration capabilities",
    topVendors: ["HP", "Dell", "Microsoft", "Cisco", "Apple", "Lenovo"],
    topCustomers: ["SMB", "State/Local Government", "Education"],
    yearFounded: 1982,
    description: "Public company providing IT solutions across three segments: Business Solutions, Enterprise Solutions, and Public Sector Solutions. Known for efficient procurement and configuration services.",
    dataSources: ["var-directory"],
    confidenceScore: 0.95,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 42.8648,
    longitude: -71.4937,
  },
  // -----------------------------------------------------------------------
  // 7. Zones — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Zones",
    website: "zones.com",
    hqCity: "Auburn",
    hqState: "WA",
    annualRevenue: 2500,
    profit: null,
    employeeCount: 2000,
    ownershipType: "Private",
    strategicSpecialty: "Global IT Solutions",
    strategicFocus: "Hardware, software, cloud, and IT services with expertise in workplace modernization and data center solutions",
    topVendors: ["Microsoft", "HP", "Dell", "Cisco", "Lenovo", "Apple"],
    topCustomers: ["Enterprise", "Education", "Government"],
    yearFounded: 1986,
    description: "Global IT solutions provider offering hardware, software, cloud, and services. Known for workplace modernization, cloud solutions, and strong OEM partnerships.",
    dataSources: ["var-directory"],
    confidenceScore: 0.8,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 47.3073,
    longitude: -122.2285,
  },
  // -----------------------------------------------------------------------
  // 8. ePlus — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "ePlus",
    website: "eplus.com",
    hqCity: "Herndon",
    hqState: "VA",
    annualRevenue: 2100,
    profit: 110,
    employeeCount: 1900,
    ownershipType: "Public",
    strategicSpecialty: "Security & Cloud",
    strategicFocus: "Security-first approach to IT solutions, cloud consulting, managed services, and financial solutions for mid-market and enterprise",
    topVendors: ["Cisco", "Palo Alto Networks", "Dell", "HPE", "Nutanix", "NetApp"],
    topCustomers: ["Mid-Market Enterprise", "Federal Government", "SLED"],
    yearFounded: 1990,
    description: "Public company providing technology and financing solutions. Combines technology product sales with professional services, managed services, and IT financing.",
    dataSources: ["var-directory"],
    confidenceScore: 0.95,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 38.9696,
    longitude: -77.3861,
  },
  // -----------------------------------------------------------------------
  // 9. Logicalis US — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Logicalis US",
    website: "logicalis.com",
    hqCity: "Farmington Hills",
    hqState: "MI",
    annualRevenue: 2000,
    profit: null,
    employeeCount: 7000,
    ownershipType: "PE",
    strategicSpecialty: "Digital Transformation",
    strategicFocus: "Cloud-first managed services, network infrastructure, and digital workplace solutions for global enterprises",
    topVendors: ["Cisco", "Microsoft", "IBM", "Dell", "HPE", "Fortinet"],
    topCustomers: ["Global Enterprise", "Education", "Healthcare"],
    yearFounded: 1997,
    description: "International IT solutions and managed services provider owned by Datatec. Focuses on cloud, security, and network infrastructure with operations in the US, Europe, and Latin America.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.8,
    growthRate: 6,
    ebitdaMargin: 9,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Managed Services", "Networking", "Collaboration"],
    latitude: 42.4853,
    longitude: -83.3771,
  },
  // -----------------------------------------------------------------------
  // 10. Trace3 — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Trace3",
    website: "trace3.com",
    hqCity: "Irvine",
    hqState: "CA",
    annualRevenue: 1200,
    profit: null,
    employeeCount: 900,
    ownershipType: "Private",
    strategicSpecialty: "Emerging Technology",
    strategicFocus: "Innovation-focused IT advisory and engineering services, AI/ML, data analytics, cloud, and cybersecurity",
    topVendors: ["Dell", "HPE", "Palo Alto Networks", "Nutanix", "Pure Storage", "Rubrik"],
    topCustomers: ["Enterprise", "Technology", "Financial Services"],
    yearFounded: 2002,
    description: "Technology solutions integrator focused on helping enterprises adopt emerging and disruptive technologies. Known for innovation workshops, AI/ML practices, and data center transformation.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.8,
    growthRate: 18,
    ebitdaMargin: 14,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Data Center", "AI/ML", "Cybersecurity"],
    latitude: 33.6846,
    longitude: -117.8265,
  },
  // -----------------------------------------------------------------------
  // 11. Softchoice — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Softchoice",
    website: "softchoice.com",
    hqCity: "Chicago",
    hqState: "IL",
    annualRevenue: 1100,
    profit: null,
    employeeCount: 1500,
    ownershipType: "Public",
    strategicSpecialty: "Cloud & Software Advisory",
    strategicFocus: "Cloud migration, software asset management, digital workplace, and IT optimization for mid-market",
    topVendors: ["Microsoft", "AWS", "Google Cloud", "Cisco", "VMware", "Adobe"],
    topCustomers: ["Mid-Market Enterprise", "Financial Services", "Manufacturing"],
    yearFounded: 1989,
    description: "Software-focused technology solutions provider publicly traded on TSX. Specializes in cloud advisory, software asset management, and digital workplace transformation.",
    dataSources: ["var-directory"],
    confidenceScore: 0.85,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 41.8781,
    longitude: -87.6298,
  },
  // -----------------------------------------------------------------------
  // 12. Dasher Technologies — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Dasher Technologies",
    website: "dasher.com",
    hqCity: "Campbell",
    hqState: "CA",
    annualRevenue: 800,
    profit: null,
    employeeCount: 250,
    ownershipType: "Private",
    strategicSpecialty: "Data Center & Cloud",
    strategicFocus: "Data center infrastructure, cloud architecture, storage, networking, and professional services for West Coast enterprises",
    topVendors: ["Dell", "HPE", "Pure Storage", "Nutanix", "Cisco", "Arista"],
    topCustomers: ["Technology Companies", "Enterprise", "Higher Education"],
    yearFounded: 1999,
    description: "Silicon Valley-based IT solutions provider specializing in data center, cloud, and infrastructure solutions. Known for deep technical engineering talent and West Coast enterprise relationships.",
    dataSources: ["var-directory"],
    confidenceScore: 0.75,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 37.2872,
    longitude: -121.9500,
  },
  // -----------------------------------------------------------------------
  // 13. Mainline Information Systems — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Mainline Information Systems",
    website: "mainline.com",
    hqCity: "Tallahassee",
    hqState: "FL",
    annualRevenue: 750,
    profit: null,
    employeeCount: 500,
    ownershipType: "Private",
    strategicSpecialty: "Enterprise Infrastructure",
    strategicFocus: "IBM-centric infrastructure solutions, hybrid cloud, storage, and mainframe modernization",
    topVendors: ["IBM", "Dell", "Cisco", "Pure Storage", "Lenovo", "Cohesity"],
    topCustomers: ["Banking & Finance", "Government", "Healthcare"],
    yearFounded: 1989,
    description: "Employee-owned IT solutions provider with deep IBM expertise. Focuses on enterprise infrastructure, hybrid cloud, data protection, and mainframe modernization.",
    dataSources: ["var-directory"],
    confidenceScore: 0.75,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 30.4383,
    longitude: -84.2807,
  },
  // -----------------------------------------------------------------------
  // 14. NWN Carousel — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "NWN Carousel",
    website: "nwncarousel.com",
    hqCity: "Exeter",
    hqState: "RI",
    annualRevenue: 700,
    profit: null,
    employeeCount: 900,
    ownershipType: "PE",
    strategicSpecialty: "Unified Communications",
    strategicFocus: "Cloud communications, collaboration, contact center, security, and managed services for enterprise",
    topVendors: ["Cisco", "Microsoft", "Poly", "Palo Alto Networks", "Genesys", "Zoom"],
    topCustomers: ["Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 1992,
    description: "PE-backed provider formed from merger of NWN and Carousel Industries. Specializes in cloud communications, managed services, and collaboration solutions with strong Cisco UC expertise.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.8,
    growthRate: 11,
    ebitdaMargin: 10,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Collaboration", "Managed Services", "Networking"],
    latitude: 41.5771,
    longitude: -71.5339,
  },
  // -----------------------------------------------------------------------
  // 15. GDT (General Datatech) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "GDT (General Datatech)",
    website: "gdt.com",
    hqCity: "Dallas",
    hqState: "TX",
    annualRevenue: 650,
    profit: null,
    employeeCount: 500,
    ownershipType: "PE",
    strategicSpecialty: "Network & Security",
    strategicFocus: "Network infrastructure, cybersecurity, cloud, and managed SD-WAN services for enterprise",
    topVendors: ["Cisco", "Fortinet", "Palo Alto Networks", "HPE Aruba", "VMware", "Juniper"],
    topCustomers: ["Enterprise", "Financial Services", "Retail"],
    yearFounded: 1984,
    description: "PE-backed IT solutions provider specializing in network infrastructure, cybersecurity, and cloud solutions. Known for managed SD-WAN and SASE capabilities.",
    dataSources: ["var-directory"],
    confidenceScore: 0.75,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 32.7767,
    longitude: -96.797,
  },
  // -----------------------------------------------------------------------
  // 16. Myriad360 — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Myriad360",
    website: "myriad360.com",
    hqCity: "New York",
    hqState: "NY",
    annualRevenue: 500,
    profit: null,
    employeeCount: 300,
    ownershipType: "Private",
    strategicSpecialty: "Cybersecurity",
    strategicFocus: "Security-first IT solutions, managed security services, cloud security, and compliance-driven infrastructure",
    topVendors: ["Palo Alto Networks", "CrowdStrike", "Fortinet", "Cisco", "Microsoft", "Okta"],
    topCustomers: ["Financial Services", "Legal", "Enterprise"],
    yearFounded: 2014,
    description: "Security-focused IT solutions provider based in New York. Combines deep cybersecurity expertise with infrastructure and cloud services for security-conscious enterprises.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 40.7128,
    longitude: -74.006,
  },
  // -----------------------------------------------------------------------
  // 17. Evolve IP — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Evolve IP",
    website: "evolveip.net",
    hqCity: "Wayne",
    hqState: "PA",
    annualRevenue: 200,
    profit: null,
    employeeCount: 400,
    ownershipType: "PE",
    strategicSpecialty: "Cloud Services",
    strategicFocus: "Cloud workspace, communications, collaboration, and contact center as a service for mid-market",
    topVendors: ["Microsoft", "Cisco", "Genesys", "VMware", "Citrix", "Zoom"],
    topCustomers: ["Mid-Market", "Healthcare", "Financial Services"],
    yearFounded: 2007,
    description: "PE-backed cloud services provider delivering unified cloud workspace, communications, and contact center solutions. Focuses on work-anywhere enablement for mid-market companies.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.7,
    growthRate: 11,
    ebitdaMargin: 18,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Unified Communications", "Managed Services", "Disaster Recovery"],
    latitude: 40.0439,
    longitude: -75.3879,
  },
  // -----------------------------------------------------------------------
  // 18. Avanade — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Avanade",
    website: "avanade.com",
    hqCity: "Seattle",
    hqState: "WA",
    annualRevenue: 4000,
    profit: null,
    employeeCount: 60000,
    ownershipType: "Private",
    strategicSpecialty: "Microsoft Solutions",
    strategicFocus: "Microsoft-centric digital transformation, Azure, Dynamics 365, Power Platform, and AI-driven innovation",
    topVendors: ["Microsoft"],
    topCustomers: ["Global Enterprise", "Financial Services", "Manufacturing"],
    yearFounded: 2000,
    description: "Joint venture between Accenture and Microsoft, specializing exclusively in the Microsoft ecosystem. Largest dedicated Microsoft partner globally, delivering cloud, AI, and business solutions.",
    dataSources: ["var-directory"],
    confidenceScore: 0.9,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 47.6062,
    longitude: -122.3321,
  },
  // -----------------------------------------------------------------------
  // 19. Computacenter — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Computacenter",
    website: "computacenter.com",
    hqCity: "Irving",
    hqState: "TX",
    annualRevenue: 1800,
    profit: null,
    employeeCount: 2500,
    ownershipType: "Public",
    strategicSpecialty: "Workplace & Infrastructure",
    strategicFocus: "Technology sourcing, workplace services, cloud infrastructure, and managed services for large enterprises",
    topVendors: ["HP", "Lenovo", "Microsoft", "Dell", "Cisco", "VMware"],
    topCustomers: ["Global Enterprise", "Public Sector", "Manufacturing"],
    yearFounded: 1981,
    description: "UK-headquartered, publicly traded IT services company with significant US operations. Specializes in technology sourcing, digital workplace, and infrastructure services.",
    dataSources: ["var-directory"],
    confidenceScore: 0.85,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 32.814,
    longitude: -96.9489,
  },
  // -----------------------------------------------------------------------
  // 20. Pomeroy — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Pomeroy",
    website: "pomeroy.com",
    hqCity: "Hebron",
    hqState: "KY",
    annualRevenue: 350,
    profit: null,
    employeeCount: 800,
    ownershipType: "PE",
    strategicSpecialty: "IT Staffing & Services",
    strategicFocus: "IT staffing, managed services, help desk, field services, and technology deployment at scale",
    topVendors: ["HP", "Dell", "Microsoft", "Cisco", "Lenovo", "Apple"],
    topCustomers: ["Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 1981,
    description: "IT services provider focused on staffing, managed services, and technology deployment. Known for nationwide field services capability and IT lifecycle management.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 39.0656,
    longitude: -84.7155,
  },
  // -----------------------------------------------------------------------
  // 21. Sirius Computer Solutions (CDW) — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Sirius Computer Solutions (CDW)",
    website: "siriuscom.com",
    hqCity: "San Antonio",
    hqState: "TX",
    annualRevenue: 2500,
    profit: null,
    employeeCount: 2700,
    ownershipType: "Public",
    strategicSpecialty: "Infrastructure & Security",
    strategicFocus: "IT infrastructure, security, cloud, and managed services — now operating as CDW's solutions subsidiary",
    topVendors: ["Dell", "Cisco", "HPE", "IBM", "Palo Alto Networks", "NetApp"],
    topCustomers: ["Enterprise", "Healthcare", "Government"],
    yearFounded: 1980,
    description: "Acquired by CDW in 2021 for $2.5B. Operates as a subsidiary focused on complex IT infrastructure, security, and hybrid cloud solutions. Retains separate brand for enterprise segment.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.85,
    growthRate: 8,
    ebitdaMargin: 9,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Cybersecurity", "Managed Services", "Data Center"],
    latitude: 29.4241,
    longitude: -98.4936,
  },
  // -----------------------------------------------------------------------
  // 22. Converge Technology Solutions — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Converge Technology Solutions",
    website: "convergetp.com",
    hqCity: "Gatineau",
    hqState: "NY",
    annualRevenue: 2200,
    profit: null,
    employeeCount: 2500,
    ownershipType: "Public",
    strategicSpecialty: "Hybrid IT & Analytics",
    strategicFocus: "Regional VAR rollup strategy, hybrid cloud, analytics, cybersecurity, and managed services across North America",
    topVendors: ["Cisco", "Dell", "HPE", "Microsoft", "IBM", "Nutanix"],
    topCustomers: ["Mid-Market Enterprise", "Public Sector", "Healthcare"],
    yearFounded: 2017,
    description: "Publicly traded buy-and-build IT solutions aggregator. Has acquired numerous regional VARs across North America to create national scale with local expertise in hybrid cloud, security, and analytics.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.8,
    growthRate: 22,
    ebitdaMargin: 8,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Cybersecurity", "Managed Services", "Analytics"],
    latitude: 40.7128,
    longitude: -74.006,
  },
  // -----------------------------------------------------------------------
  // 23. Ahead — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Ahead",
    website: "ahead.com",
    hqCity: "Chicago",
    hqState: "IL",
    annualRevenue: 700,
    profit: null,
    employeeCount: 600,
    ownershipType: "PE",
    strategicSpecialty: "Cloud & Digital Infrastructure",
    strategicFocus: "Cloud transformation, data center modernization, security, and managed infrastructure for mid-market and enterprise",
    topVendors: ["Dell", "HPE", "Cisco", "Nutanix", "Pure Storage", "VMware"],
    topCustomers: ["Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 2007,
    description: "PE-backed IT solutions provider based in Chicago focusing on cloud, data center, and digital infrastructure. Known for engineering-led approach and deep hybrid cloud expertise.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.75,
    growthRate: 24,
    ebitdaMargin: 14,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Data Analytics", "Managed Services", "Security"],
    latitude: 41.8781,
    longitude: -87.6298,
  },
  // -----------------------------------------------------------------------
  // 24. Flexential — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Flexential",
    website: "flexential.com",
    hqCity: "Charlotte",
    hqState: "NC",
    annualRevenue: 500,
    profit: null,
    employeeCount: 800,
    ownershipType: "PE",
    strategicSpecialty: "Colocation & Cloud",
    strategicFocus: "Data center colocation, hybrid cloud, connectivity, and managed hosting services across 40+ US data centers",
    topVendors: ["VMware", "Dell", "Cisco", "Juniper", "Palo Alto Networks", "AWS"],
    topCustomers: ["Enterprise", "Financial Services", "SaaS Companies"],
    yearFounded: 2017,
    description: "PE-backed data center services provider formed from merger of Peak 10 and ViaWest. Operates 40+ data centers across the US providing colocation, cloud, and interconnection services.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.75,
    growthRate: 14,
    ebitdaMargin: 22,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Colocation", "Managed Services", "Data Protection"],
    latitude: 35.2271,
    longitude: -80.8431,
  },
  // -----------------------------------------------------------------------
  // 25. Sentinel Technologies — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Sentinel Technologies",
    website: "sentinel.com",
    hqCity: "Downers Grove",
    hqState: "IL",
    annualRevenue: 550,
    profit: null,
    employeeCount: 500,
    ownershipType: "PE",
    strategicSpecialty: "Managed Services",
    strategicFocus: "Managed IT services, security, cloud, and infrastructure solutions for mid-market enterprises in the Midwest",
    topVendors: ["Cisco", "Dell", "HPE", "Palo Alto Networks", "Microsoft", "VMware"],
    topCustomers: ["Mid-Market Enterprise", "Manufacturing", "Financial Services"],
    yearFounded: 1982,
    description: "PE-backed Midwest-focused IT solutions provider offering managed services, cybersecurity, cloud, and infrastructure. Known for high-touch service delivery in the Chicago region.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.7,
    growthRate: 12,
    ebitdaMargin: 13,
    customerSegment: "Mid-Market",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Networking"],
    latitude: 41.7509,
    longitude: -88.0012,
  },
  // -----------------------------------------------------------------------
  // 26. BlueAlly Technology Solutions — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "BlueAlly Technology Solutions",
    website: "blueally.com",
    hqCity: "Morrisville",
    hqState: "NC",
    annualRevenue: 50,
    profit: null,
    employeeCount: 100,
    ownershipType: "Private",
    strategicSpecialty: "AI & Data Analytics",
    strategicFocus: "AI-powered IT consulting, data analytics, cloud migration, and managed services for mid-market",
    topVendors: ["Microsoft", "AWS", "Dell", "Cisco", "Anthropic", "ServiceNow"],
    topCustomers: ["Mid-Market Enterprise", "PE Portfolio Companies", "Healthcare"],
    yearFounded: 2014,
    description: "AI-forward IT solutions and consulting firm based in the Research Triangle. Specializes in AI implementation, data analytics, cloud transformation, and managed services for PE portfolio companies.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 35.8235,
    longitude: -78.8256,
  },
  // -----------------------------------------------------------------------
  // 27. Datalink (Insight) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Datalink (Insight)",
    website: "datalink.com",
    hqCity: "Chanhassen",
    hqState: "MN",
    annualRevenue: 600,
    profit: null,
    employeeCount: 400,
    ownershipType: "Public",
    strategicSpecialty: "Data Center Solutions",
    strategicFocus: "Data center architecture, storage, virtualization, and hybrid cloud — operating under Insight Enterprises",
    topVendors: ["Dell", "HPE", "NetApp", "VMware", "Nutanix", "Cisco"],
    topCustomers: ["Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 2003,
    description: "Acquired by Insight Enterprises in 2017. Originally a Minnesota-based data center solutions provider known for deep storage and virtualization expertise. Now part of Insight's solutions portfolio.",
    dataSources: ["var-directory"],
    confidenceScore: 0.75,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 44.8622,
    longitude: -93.5308,
  },
  // -----------------------------------------------------------------------
  // 28. ConvergeOne — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "ConvergeOne",
    website: "convergeone.com",
    hqCity: "Eagan",
    hqState: "MN",
    annualRevenue: 1000,
    profit: null,
    employeeCount: 1200,
    ownershipType: "PE",
    strategicSpecialty: "Collaboration & Contact Center",
    strategicFocus: "Unified communications, contact center, cloud collaboration, and managed services for enterprise",
    topVendors: ["Avaya", "Cisco", "Genesys", "Microsoft", "AWS", "RingCentral"],
    topCustomers: ["Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 1993,
    description: "PE-backed IT solutions provider specializing in collaboration, communications, and contact center technology. Largest independent Avaya partner in the US.",
    dataSources: ["var-directory"],
    confidenceScore: 0.8,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 44.804,
    longitude: -93.1669,
  },
  // -----------------------------------------------------------------------
  // 29. PCM (Insight) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "PCM (Insight)",
    website: "pcm.com",
    hqCity: "El Segundo",
    hqState: "CA",
    annualRevenue: 2000,
    profit: null,
    employeeCount: 3500,
    ownershipType: "Public",
    strategicSpecialty: "IT Procurement & Services",
    strategicFocus: "End-to-end IT procurement, cloud, managed services, and staffing — now operating under Insight",
    topVendors: ["HP", "Microsoft", "Dell", "Cisco", "Lenovo", "Apple"],
    topCustomers: ["Enterprise", "SMB", "Public Sector"],
    yearFounded: 1987,
    description: "Acquired by Insight Enterprises in 2019 for $581M. Was one of the largest direct marketers of technology products in the US. Strengthened Insight's commercial and SMB reach.",
    dataSources: ["var-directory"],
    confidenceScore: 0.8,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 33.9192,
    longitude: -118.4165,
  },
  // -----------------------------------------------------------------------
  // 30. Technologent — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Technologent",
    website: "technologent.com",
    hqCity: "Irvine",
    hqState: "CA",
    annualRevenue: 450,
    profit: null,
    employeeCount: 250,
    ownershipType: "Private",
    strategicSpecialty: "Data Center & Storage",
    strategicFocus: "Enterprise data center infrastructure, storage, virtualization, and professional services on the West Coast",
    topVendors: ["Dell", "HPE", "Pure Storage", "Cisco", "NetApp", "Rubrik"],
    topCustomers: ["Entertainment", "Technology", "Financial Services"],
    yearFounded: 2003,
    description: "Woman-owned enterprise IT solutions provider based in Southern California. Specializes in data center, storage, and compute solutions with deep engineering capabilities.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 33.6846,
    longitude: -117.8265,
  },
  // -----------------------------------------------------------------------
  // 31. Advizex (Insight) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Advizex (Insight)",
    website: "advizex.com",
    hqCity: "Cleveland",
    hqState: "OH",
    annualRevenue: 400,
    profit: null,
    employeeCount: 250,
    ownershipType: "Public",
    strategicSpecialty: "Hybrid Cloud",
    strategicFocus: "Hybrid cloud, infrastructure modernization, and managed services — now operating under Insight",
    topVendors: ["Dell", "HPE", "Cisco", "Nutanix", "VMware", "Pure Storage"],
    topCustomers: ["Enterprise", "Manufacturing", "Healthcare"],
    yearFounded: 1984,
    description: "Acquired by Insight Enterprises. Originally Cleveland-based data center and hybrid cloud solutions provider known for deep Midwest enterprise relationships and engineering expertise.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 41.4993,
    longitude: -81.6944,
  },
  // -----------------------------------------------------------------------
  // 32. ACI (Agilant Solutions) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "ACI (Agilant Solutions)",
    website: "acit.com",
    hqCity: "Orlando",
    hqState: "FL",
    annualRevenue: 300,
    profit: null,
    employeeCount: 200,
    ownershipType: "Private",
    strategicSpecialty: "Professional AV & Collaboration",
    strategicFocus: "Audio-visual integration, collaboration spaces, digital signage, and unified communications deployment",
    topVendors: ["Crestron", "Cisco", "Poly", "Microsoft", "Extron", "QSC"],
    topCustomers: ["Corporate", "Education", "Government"],
    yearFounded: 1998,
    description: "AV-centric IT solutions provider specializing in professional audio-visual integration, collaboration spaces, and digital workplace environments for corporate and education sectors.",
    dataSources: ["var-directory"],
    confidenceScore: 0.65,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 28.5383,
    longitude: -81.3792,
  },
  // -----------------------------------------------------------------------
  // 33. Viavi Solutions (Optical) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Viavi Solutions (Optical)",
    website: "viavisolutions.com",
    hqCity: "Chandler",
    hqState: "AZ",
    annualRevenue: 1100,
    profit: 80,
    employeeCount: 3300,
    ownershipType: "Public",
    strategicSpecialty: "Network Test & Measurement",
    strategicFocus: "Network test and measurement, fiber optics, 5G validation, and optical products for telecom and enterprise",
    topVendors: ["Proprietary Technology"],
    topCustomers: ["Telecom Carriers", "Cable Operators", "Government"],
    yearFounded: 2005,
    description: "Public company providing network test, measurement, and assurance solutions. Serves telecom carriers, cable operators, and enterprise customers with fiber, 5G, and network monitoring tools.",
    dataSources: ["var-directory"],
    confidenceScore: 0.85,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 33.3062,
    longitude: -111.8413,
  },
  // -----------------------------------------------------------------------
  // 34. Optiv Security — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Optiv Security",
    website: "optiv.com",
    hqCity: "Denver",
    hqState: "CO",
    annualRevenue: 2400,
    profit: null,
    employeeCount: 2200,
    ownershipType: "PE",
    strategicSpecialty: "Cybersecurity",
    strategicFocus: "End-to-end cybersecurity solutions, managed security services, identity, cloud security, and threat management",
    topVendors: ["CrowdStrike", "Palo Alto Networks", "Splunk", "Okta", "Microsoft", "SailPoint"],
    topCustomers: ["Enterprise", "Financial Services", "Healthcare"],
    yearFounded: 2015,
    description: "Largest pure-play cybersecurity solutions integrator in the US. PE-backed (KKR). Provides comprehensive security advisory, implementation, managed security, and threat management services.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.85,
    growthRate: 15,
    ebitdaMargin: 13,
    customerSegment: "Enterprise",
    specialties: ["Cybersecurity", "Identity", "Cloud Security", "Managed Detection"],
    latitude: 39.7392,
    longitude: -104.9903,
  },
  // -----------------------------------------------------------------------
  // 35. OneNeck IT Solutions — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "OneNeck IT Solutions",
    website: "oneneck.com",
    hqCity: "Scottsdale",
    hqState: "AZ",
    annualRevenue: 350,
    profit: null,
    employeeCount: 400,
    ownershipType: "Private",
    strategicSpecialty: "Managed Hosting",
    strategicFocus: "Managed hosting, cloud, ERP hosting (JD Edwards/Oracle), and IT managed services",
    topVendors: ["Dell", "Cisco", "VMware", "Oracle", "Microsoft", "AWS"],
    topCustomers: ["Mid-Market", "Manufacturing", "Distribution"],
    yearFounded: 2003,
    description: "Subsidiary of Telephone and Data Systems (TDS). Specializes in managed hosting, cloud infrastructure, ERP hosting, and IT managed services for mid-market companies.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.7,
    growthRate: 7,
    ebitdaMargin: 16,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Managed Services", "Data Center", "ERP Hosting"],
    latitude: 33.4942,
    longitude: -111.9261,
  },
  // -----------------------------------------------------------------------
  // 36. Mythics — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Mythics",
    website: "mythics.com",
    hqCity: "Virginia Beach",
    hqState: "VA",
    annualRevenue: 500,
    profit: null,
    employeeCount: 350,
    ownershipType: "Private",
    strategicSpecialty: "Oracle Solutions",
    strategicFocus: "Oracle-centric cloud, infrastructure, database, and application solutions for federal and commercial markets",
    topVendors: ["Oracle", "Dell", "AWS", "Cisco", "NetApp"],
    topCustomers: ["Federal Government", "State/Local Government", "Enterprise"],
    yearFounded: 2000,
    description: "Oracle Platinum Partner specializing in Oracle Cloud, database, middleware, and hardware solutions. Strong federal and public sector practice with deep Oracle expertise.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 36.8529,
    longitude: -75.978,
  },
  // -----------------------------------------------------------------------
  // 37. Meridian IT — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Meridian IT",
    website: "meridianit.com",
    hqCity: "Libertyville",
    hqState: "IL",
    annualRevenue: 400,
    profit: null,
    employeeCount: 300,
    ownershipType: "PE",
    strategicSpecialty: "IT Lifecycle Management",
    strategicFocus: "IT asset disposition, lifecycle management, refurbished hardware, and sustainability-focused IT services",
    topVendors: ["Dell", "HP", "Lenovo", "Cisco", "Apple", "Microsoft"],
    topCustomers: ["Enterprise", "Education", "Government"],
    yearFounded: 1985,
    description: "PE-backed IT solutions provider with unique ITAD (IT Asset Disposition) and lifecycle management capabilities. Combines new technology sales with sustainable IT disposition services.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 42.2828,
    longitude: -87.953,
  },
  // -----------------------------------------------------------------------
  // 38. Core BTS — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Core BTS",
    website: "corebts.com",
    hqCity: "Indianapolis",
    hqState: "IN",
    annualRevenue: 250,
    profit: null,
    employeeCount: 300,
    ownershipType: "PE",
    strategicSpecialty: "Cloud & Digital Workplace",
    strategicFocus: "Microsoft-centric cloud transformation, digital workplace, cybersecurity, and managed services",
    topVendors: ["Microsoft", "Cisco", "Palo Alto Networks", "VMware", "Dell", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Manufacturing", "Healthcare"],
    yearFounded: 1995,
    description: "PE-backed IT solutions provider focused on Microsoft cloud transformation, digital workplace, and cybersecurity. Strong Midwest regional presence with national managed services.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 39.7684,
    longitude: -86.1581,
  },
  // -----------------------------------------------------------------------
  // 39. Aqueduct Technologies — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Aqueduct Technologies",
    website: "aqueducttech.com",
    hqCity: "Waltham",
    hqState: "MA",
    annualRevenue: 200,
    profit: null,
    employeeCount: 150,
    ownershipType: "Private",
    strategicSpecialty: "Network & Security",
    strategicFocus: "Network infrastructure, cybersecurity, SD-WAN, and professional services for Northeast enterprise",
    topVendors: ["Cisco", "Palo Alto Networks", "Fortinet", "HPE Aruba", "Juniper", "F5"],
    topCustomers: ["Enterprise", "Financial Services", "Education"],
    yearFounded: 2006,
    description: "New England-based IT solutions provider specializing in network infrastructure, cybersecurity, and cloud. Known for deep Cisco and Palo Alto Networks expertise in the Northeast.",
    dataSources: ["var-directory"],
    confidenceScore: 0.65,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 42.3765,
    longitude: -71.2356,
  },
  // -----------------------------------------------------------------------
  // 40. CBTS (Cincinnati Bell Technology Solutions) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "CBTS (Cincinnati Bell Technology Solutions)",
    website: "cbts.com",
    hqCity: "Cincinnati",
    hqState: "OH",
    annualRevenue: 800,
    profit: null,
    employeeCount: 1000,
    ownershipType: "Private",
    strategicSpecialty: "Communications & Cloud",
    strategicFocus: "UCaaS, CCaaS, SD-WAN, cybersecurity, and managed infrastructure services for mid-market and enterprise",
    topVendors: ["Cisco", "Microsoft", "Genesys", "Fortinet", "Dell", "VMware"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 2007,
    description: "IT solutions subsidiary of Cincinnati Bell (now altafiber). Provides unified communications, contact center, SD-WAN, and managed services. Strong Midwest and Southeast presence.",
    dataSources: ["var-directory"],
    confidenceScore: 0.75,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 39.1031,
    longitude: -84.512,
  },
  // -----------------------------------------------------------------------
  // 41. Crayon — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Crayon",
    website: "crayon.com",
    hqCity: "Houston",
    hqState: "TX",
    annualRevenue: 600,
    profit: null,
    employeeCount: 500,
    ownershipType: "Public",
    strategicSpecialty: "Software & Cloud Economics",
    strategicFocus: "Cloud economics, software asset management, FinOps, and cloud optimization for global enterprises",
    topVendors: ["Microsoft", "AWS", "Google Cloud", "Adobe", "SAP", "Oracle"],
    topCustomers: ["Global Enterprise", "Financial Services", "Energy"],
    yearFounded: 2002,
    description: "Norwegian-headquartered, publicly traded IT advisory firm with growing US operations. Specializes in cloud economics, software licensing optimization, and FinOps advisory.",
    dataSources: ["var-directory"],
    confidenceScore: 0.75,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 29.7604,
    longitude: -95.3698,
  },
  // -----------------------------------------------------------------------
  // 42. Lumen Technologies — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Lumen Technologies",
    website: "lumen.com",
    hqCity: "Monroe",
    hqState: "LA",
    annualRevenue: 14000,
    profit: null,
    employeeCount: 30000,
    ownershipType: "Public",
    strategicSpecialty: "Network & Edge",
    strategicFocus: "Fiber networking, edge compute, security, and application delivery platform for global enterprises",
    topVendors: ["Cisco", "Juniper", "Fortinet", "Microsoft", "VMware", "AWS"],
    topCustomers: ["Global Enterprise", "Government", "Wholesale Carriers"],
    yearFounded: 1930,
    description: "Major telecom and IT solutions provider offering enterprise fiber networking, edge computing, security, and collaboration services. Transitioning from legacy telco to platform-based solutions company.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.9,
    growthRate: 3,
    ebitdaMargin: 7,
    customerSegment: "Enterprise",
    specialties: ["Networking", "Cloud", "Edge Computing", "Security"],
    latitude: 32.5093,
    longitude: -92.1193,
  },
  // -----------------------------------------------------------------------
  // 43. Logista Solutions — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Logista Solutions",
    website: "logistasolutions.com",
    hqCity: "Tampa",
    hqState: "FL",
    annualRevenue: 200,
    profit: null,
    employeeCount: 150,
    ownershipType: "Private",
    strategicSpecialty: "IT Deployment Services",
    strategicFocus: "Large-scale IT deployment, rollout services, field services, and technology refresh for retail and enterprise",
    topVendors: ["HP", "Dell", "Lenovo", "Zebra", "Cisco", "Epson"],
    topCustomers: ["Retail", "Hospitality", "Healthcare"],
    yearFounded: 2010,
    description: "IT deployment and field services company specializing in large-scale technology rollouts for retail, hospitality, and healthcare. Provides nationwide break/fix and deployment services.",
    dataSources: ["var-directory"],
    confidenceScore: 0.65,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 27.9506,
    longitude: -82.4572,
  },
  // -----------------------------------------------------------------------
  // 44. Compugen — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Compugen",
    website: "compugen.com",
    hqCity: "Richmond Hill",
    hqState: "NY",
    annualRevenue: 900,
    profit: null,
    employeeCount: 800,
    ownershipType: "Private",
    strategicSpecialty: "End-User Computing",
    strategicFocus: "Digital workplace, device lifecycle, cloud, and managed services for enterprises across North America",
    topVendors: ["HP", "Dell", "Lenovo", "Microsoft", "Cisco", "Apple"],
    topCustomers: ["Enterprise", "Education", "Government"],
    yearFounded: 1981,
    description: "Canadian-headquartered IT solutions provider with US operations. Specializes in end-user computing, device lifecycle management, cloud, and digital workplace transformation.",
    dataSources: ["var-directory"],
    confidenceScore: 0.7,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 40.7128,
    longitude: -74.006,
  },
  // -----------------------------------------------------------------------
  // 45. Datacom — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Datacom",
    website: "dtcom.com",
    hqCity: "East Rutherford",
    hqState: "NJ",
    annualRevenue: 180,
    profit: null,
    employeeCount: 120,
    ownershipType: "Private",
    strategicSpecialty: "Network Infrastructure",
    strategicFocus: "Network design, structured cabling, data center build, and infrastructure deployment for enterprise",
    topVendors: ["Cisco", "CommScope", "Corning", "Panduit", "Dell", "HPE"],
    topCustomers: ["Enterprise", "Financial Services", "Government"],
    yearFounded: 1983,
    description: "Northeast-based network infrastructure and structured cabling solutions provider. Specializes in data center builds, network design, and physical infrastructure deployment.",
    dataSources: ["var-directory"],
    confidenceScore: 0.6,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 40.834,
    longitude: -74.097,
  },
  // -----------------------------------------------------------------------
  // 46. Arctiq — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Arctiq",
    website: "arctiq.com",
    hqCity: "Chicago",
    hqState: "IL",
    annualRevenue: 150,
    profit: null,
    employeeCount: 200,
    ownershipType: "Private",
    strategicSpecialty: "DevSecOps & Automation",
    strategicFocus: "Kubernetes, DevSecOps, infrastructure automation, and cloud-native transformation for enterprises",
    topVendors: ["Red Hat", "HashiCorp", "Cisco", "Palo Alto Networks", "Microsoft", "AWS"],
    topCustomers: ["Enterprise", "Financial Services", "Technology"],
    yearFounded: 2015,
    description: "Cloud-native IT solutions provider focusing on Kubernetes, DevSecOps, and infrastructure automation. Helps enterprises adopt modern application platforms and zero-trust security.",
    dataSources: ["var-directory"],
    confidenceScore: 0.6,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 41.8781,
    longitude: -87.6298,
  },
  // -----------------------------------------------------------------------
  // 47. Strategic Communications — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Strategic Communications",
    website: "stratcomm.com",
    hqCity: "Reno",
    hqState: "NV",
    annualRevenue: 120,
    profit: null,
    employeeCount: 100,
    ownershipType: "Private",
    strategicSpecialty: "Managed IT Services",
    strategicFocus: "Managed IT, cybersecurity, cloud, and communications for SMB and mid-market in the Western US",
    topVendors: ["Cisco", "Microsoft", "Fortinet", "Dell", "HP", "SonicWall"],
    topCustomers: ["SMB", "Gaming/Hospitality", "Government"],
    yearFounded: 1996,
    description: "Western US IT solutions provider specializing in managed services, cybersecurity, and unified communications for SMB and mid-market clients in Nevada and surrounding states.",
    dataSources: ["var-directory"],
    confidenceScore: 0.6,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 39.5296,
    longitude: -119.8138,
  },
  // -----------------------------------------------------------------------
  // 48. Anexinet (Acuative) — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Anexinet (Acuative)",
    website: "anexinet.com",
    hqCity: "Blue Bell",
    hqState: "PA",
    annualRevenue: 200,
    profit: null,
    employeeCount: 200,
    ownershipType: "PE",
    strategicSpecialty: "Digital Experience",
    strategicFocus: "Digital experience platforms, mobile development, data analytics, and cloud application modernization",
    topVendors: ["Microsoft", "AWS", "Salesforce", "Adobe", "ServiceNow", "Snowflake"],
    topCustomers: ["Enterprise", "Financial Services", "Healthcare"],
    yearFounded: 2002,
    description: "PE-backed digital solutions provider focused on customer experience, data analytics, and application modernization. Combines consulting with technical implementation for digital transformation.",
    dataSources: ["var-directory"],
    confidenceScore: 0.65,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 40.1523,
    longitude: -75.2662,
  },
  // -----------------------------------------------------------------------
  // 49. Red River Technology — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Red River Technology",
    website: "redriver.com",
    hqCity: "Claremont",
    hqState: "NH",
    annualRevenue: 1500,
    profit: null,
    employeeCount: 800,
    ownershipType: "Private",
    strategicSpecialty: "Government IT",
    strategicFocus: "Federal and SLED IT solutions, cybersecurity, cloud, and managed services with deep public sector expertise",
    topVendors: ["Dell", "Cisco", "Palo Alto Networks", "Microsoft", "VMware", "AWS"],
    topCustomers: ["Federal Government", "DoD", "State/Local Government"],
    yearFounded: 1995,
    description: "Major government-focused IT solutions provider with deep federal and SLED expertise. Provides cybersecurity, cloud, and managed services to public sector customers across the US.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.8,
    growthRate: 16,
    ebitdaMargin: 12,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Cybersecurity", "Networking", "Managed Services"],
    latitude: 43.3765,
    longitude: -72.3468,
  },
  // -----------------------------------------------------------------------
  // 50. Involta — Source 1 only
  // -----------------------------------------------------------------------
  {
    name: "Involta",
    website: "involta.com",
    hqCity: "Cedar Rapids",
    hqState: "IA",
    annualRevenue: 200,
    profit: null,
    employeeCount: 250,
    ownershipType: "PE",
    strategicSpecialty: "Hybrid IT & Colocation",
    strategicFocus: "Hybrid IT solutions, colocation, cloud, managed services, and disaster recovery for Midwest enterprises",
    topVendors: ["Dell", "Cisco", "VMware", "Zerto", "Veeam", "Microsoft"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 2007,
    description: "PE-backed hybrid IT and colocation provider operating data centers across the Midwest. Provides colocation, cloud, managed services, and disaster recovery for mid-market enterprises.",
    dataSources: ["var-directory"],
    confidenceScore: 0.65,
    growthRate: null,
    ebitdaMargin: null,
    customerSegment: null,
    specialties: null,
    latitude: 41.9779,
    longitude: -91.6656,
  },
  // -----------------------------------------------------------------------
  // 51. Burwood Group — MERGED (Source 1 + Source 2)
  // -----------------------------------------------------------------------
  {
    name: "Burwood Group",
    website: "burwood.com",
    hqCity: "Chicago",
    hqState: "IL",
    annualRevenue: 150,
    profit: null,
    employeeCount: 200,
    ownershipType: "Private",
    strategicSpecialty: "IT Consulting",
    strategicFocus: "IT strategy consulting, infrastructure, cybersecurity, and cloud solutions for Midwest enterprise and education",
    topVendors: ["Cisco", "Palo Alto Networks", "Microsoft", "Dell", "Google Cloud", "VMware"],
    topCustomers: ["Enterprise", "Higher Education", "Healthcare"],
    yearFounded: 1997,
    description: "Chicago-based IT consulting and solutions firm specializing in infrastructure, security, and cloud. Strong higher education and healthcare practices in the Midwest.",
    dataSources: ["var-directory", "ma-engine"],
    confidenceScore: 0.6,
    growthRate: 14,
    ebitdaMargin: 16,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Cybersecurity", "Networking", "Data Center"],
    latitude: 41.8781,
    longitude: -87.6298,
  },
  // -----------------------------------------------------------------------
  // 52. Rackspace Technology — Source 2 only (no Source 1 match)
  // Note: Not in Source 1 VAR_COMPANIES array. Added from M&A engine.
  // -----------------------------------------------------------------------
  {
    name: "Rackspace Technology",
    website: "rackspace.com",
    hqCity: "San Antonio",
    hqState: "TX",
    annualRevenue: 3000,
    profit: null,
    employeeCount: 6000,
    ownershipType: "PE",
    strategicSpecialty: "Multi-Cloud Managed Services",
    strategicFocus: "Multi-cloud management, managed hosting, and data solutions across AWS, Azure, and Google Cloud",
    topVendors: ["AWS", "Microsoft", "Google", "VMware"],
    topCustomers: ["Enterprise", "Mid-Market", "SaaS Companies"],
    yearFounded: 1998,
    description: "PE-backed multi-cloud technology services company providing managed cloud, professional services, and data solutions. One of the largest managed cloud providers globally.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.7,
    growthRate: 2,
    ebitdaMargin: 8,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Managed Services", "Multi-Cloud", "Data"],
    latitude: 29.4241,
    longitude: -98.4936,
  },
  // -----------------------------------------------------------------------
  // 53. Pax8 — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Pax8",
    website: "pax8.com",
    hqCity: "Denver",
    hqState: "CO",
    annualRevenue: 1600,
    profit: null,
    employeeCount: 1800,
    ownershipType: "PE",
    strategicSpecialty: "Cloud Marketplace",
    strategicFocus: "Cloud marketplace distribution, SaaS channel enablement, and managed services platform for MSPs",
    topVendors: ["Microsoft", "AWS", "Adobe", "Acronis"],
    topCustomers: ["MSPs", "SMB", "Channel Partners"],
    yearFounded: 2012,
    description: "PE-backed cloud commerce marketplace simplifying how partners buy, sell, and manage cloud solutions. Rapidly growing platform connecting cloud vendors with the MSP channel.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.7,
    growthRate: 35,
    ebitdaMargin: 6,
    customerSegment: "SMB",
    specialties: ["Cloud Marketplace", "Managed Services", "SaaS Distribution"],
    latitude: 39.7392,
    longitude: -104.9903,
  },
  // -----------------------------------------------------------------------
  // 54. Nitel — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Nitel",
    website: "nitel.com",
    hqCity: "Chicago",
    hqState: "IL",
    annualRevenue: 180,
    profit: null,
    employeeCount: 280,
    ownershipType: "PE",
    strategicSpecialty: "SD-WAN & Connectivity",
    strategicFocus: "Managed SD-WAN, UCaaS, cloud connectivity, and network-as-a-service for mid-market enterprises",
    topVendors: ["Cisco", "Microsoft", "VMware", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Multi-Location Businesses", "Retail"],
    yearFounded: 2014,
    description: "PE-backed managed network and cloud services provider specializing in SD-WAN, UCaaS, and connectivity solutions. Serves mid-market enterprises with multi-location networking needs.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 19,
    ebitdaMargin: 15,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Managed SD-WAN", "UCaaS", "Connectivity"],
    latitude: 41.8781,
    longitude: -87.6298,
  },
  // -----------------------------------------------------------------------
  // 55. MicroAge — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "MicroAge",
    website: "microage.com",
    hqCity: "Tempe",
    hqState: "AZ",
    annualRevenue: 320,
    profit: null,
    employeeCount: 350,
    ownershipType: "Private",
    strategicSpecialty: "IT Procurement & Lifecycle",
    strategicFocus: "Cloud solutions, managed services, IT procurement, and lifecycle services for mid-market enterprises",
    topVendors: ["Dell", "HP", "Microsoft", "Lenovo"],
    topCustomers: ["Mid-Market Enterprise", "Education", "Government"],
    yearFounded: 1976,
    description: "Long-standing IT solutions provider based in Arizona offering cloud, managed services, procurement, and lifecycle services. One of the original IT channel companies with deep distribution roots.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 5,
    ebitdaMargin: 8,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Managed Services", "Procurement", "Lifecycle Services"],
    latitude: 33.4255,
    longitude: -111.9400,
  },
  // -----------------------------------------------------------------------
  // 56. TBC (Technology Business Consulting) — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "TBC (Technology Business Consulting)",
    website: "tbcit.com",
    hqCity: "Raleigh",
    hqState: "NC",
    annualRevenue: 150,
    profit: null,
    employeeCount: 200,
    ownershipType: "Private",
    strategicSpecialty: "Cloud & Cybersecurity",
    strategicFocus: "Cloud migration, cybersecurity, managed services, and networking for mid-market enterprises in the Southeast",
    topVendors: ["Cisco", "Microsoft", "Dell", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Manufacturing"],
    yearFounded: 2003,
    description: "Raleigh-based IT consulting and solutions provider focused on cloud, cybersecurity, managed services, and networking. Serves mid-market enterprises in the Carolinas and Southeast region.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 13,
    ebitdaMargin: 14,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Cybersecurity", "Managed Services", "Networking"],
    latitude: 35.7796,
    longitude: -78.6382,
  },
  // -----------------------------------------------------------------------
  // 57. Coretelligent — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Coretelligent",
    website: "coretelligent.com",
    hqCity: "Westwood",
    hqState: "MA",
    annualRevenue: 85,
    profit: null,
    employeeCount: 230,
    ownershipType: "PE",
    strategicSpecialty: "Managed Services & Compliance",
    strategicFocus: "Managed IT services, cybersecurity, cloud, and compliance solutions for financial services and mid-market",
    topVendors: ["Microsoft", "Dell", "Cisco", "SentinelOne"],
    topCustomers: ["Financial Services", "Private Equity", "Professional Services"],
    yearFounded: 2006,
    description: "PE-backed managed IT services provider focused on financial services and compliance-heavy industries. Delivers white-glove managed services, cybersecurity, and cloud solutions.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 25,
    ebitdaMargin: 17,
    customerSegment: "Mid-Market",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Compliance"],
    latitude: 42.2148,
    longitude: -71.2244,
  },
  // -----------------------------------------------------------------------
  // 58. GreenPages Technology Solutions — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "GreenPages Technology Solutions",
    website: "greenpages.com",
    hqCity: "Kittery",
    hqState: "ME",
    annualRevenue: 250,
    profit: null,
    employeeCount: 300,
    ownershipType: "Private",
    strategicSpecialty: "Cloud & DevOps",
    strategicFocus: "Cloud transformation, DevOps enablement, managed services, and data center modernization for mid-market",
    topVendors: ["Dell", "VMware", "Microsoft", "AWS"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Education"],
    yearFounded: 1992,
    description: "New England-based IT solutions provider specializing in cloud, DevOps, managed services, and data center transformation. Known for strong engineering culture and mid-market focus.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 10,
    ebitdaMargin: 11,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "DevOps", "Managed Services", "Data Center"],
    latitude: 43.0884,
    longitude: -70.7367,
  },
  // -----------------------------------------------------------------------
  // 59. Marco Technologies — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Marco Technologies",
    website: "marconet.com",
    hqCity: "St. Cloud",
    hqState: "MN",
    annualRevenue: 550,
    profit: null,
    employeeCount: 1500,
    ownershipType: "ESOP",
    strategicSpecialty: "Managed Services & Print",
    strategicFocus: "Managed IT services, cloud, cybersecurity, and print management for SMB and mid-market",
    topVendors: ["Microsoft", "Dell", "Cisco", "HP"],
    topCustomers: ["SMB", "Education", "Healthcare"],
    yearFounded: 1973,
    description: "Employee-owned (ESOP) technology provider offering managed services, cloud, cybersecurity, and managed print. One of the largest ESOP IT companies in the US with strong Midwest presence.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 9,
    ebitdaMargin: 12,
    customerSegment: "SMB",
    specialties: ["Managed Services", "Cloud", "Cybersecurity", "Print Management"],
    latitude: 45.5616,
    longitude: -94.1622,
  },
  // -----------------------------------------------------------------------
  // 60. Agio — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Agio",
    website: "agio.com",
    hqCity: "New York",
    hqState: "NY",
    annualRevenue: 120,
    profit: null,
    employeeCount: 350,
    ownershipType: "PE",
    strategicSpecialty: "Financial Services IT",
    strategicFocus: "Managed services, cybersecurity, cloud, and compliance for financial services and alternative investments",
    topVendors: ["Microsoft", "CrowdStrike", "Palo Alto", "AWS"],
    topCustomers: ["Hedge Funds", "Private Equity", "Financial Services"],
    yearFounded: 2010,
    description: "PE-backed managed IT and cybersecurity provider laser-focused on financial services. Serves hedge funds, PE firms, and alternative investment managers with compliance-ready IT solutions.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 20,
    ebitdaMargin: 19,
    customerSegment: "Mid-Market",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Compliance"],
    latitude: 40.7128,
    longitude: -74.006,
  },
  // -----------------------------------------------------------------------
  // 61. Dataprise — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Dataprise",
    website: "dataprise.com",
    hqCity: "Rockville",
    hqState: "MD",
    annualRevenue: 160,
    profit: null,
    employeeCount: 500,
    ownershipType: "PE",
    strategicSpecialty: "Managed IT & Help Desk",
    strategicFocus: "Managed IT services, cybersecurity, cloud migration, and help desk support for mid-market enterprises",
    topVendors: ["Microsoft", "Dell", "Cisco", "SentinelOne"],
    topCustomers: ["Mid-Market Enterprise", "Professional Services", "Nonprofits"],
    yearFounded: 1995,
    description: "PE-backed managed IT services provider in the DC metro area. Offers managed services, cybersecurity, cloud, and 24/7 help desk support for mid-market companies and nonprofits.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 18,
    ebitdaMargin: 16,
    customerSegment: "Mid-Market",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Help Desk"],
    latitude: 39.084,
    longitude: -77.1528,
  },
  // -----------------------------------------------------------------------
  // 62. Evolving Solutions — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Evolving Solutions",
    website: "evolvingsol.com",
    hqCity: "Hamel",
    hqState: "MN",
    annualRevenue: 140,
    profit: null,
    employeeCount: 160,
    ownershipType: "Private",
    strategicSpecialty: "Data Center & Storage",
    strategicFocus: "Cloud, data center modernization, managed services, and enterprise storage solutions for mid-market",
    topVendors: ["Dell", "VMware", "Microsoft", "Pure Storage"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Manufacturing"],
    yearFounded: 1995,
    description: "Minnesota-based IT solutions provider specializing in cloud, data center, managed services, and storage. Serves mid-market enterprises in the upper Midwest with deep infrastructure expertise.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 7,
    ebitdaMargin: 10,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Data Center", "Managed Services", "Storage"],
    latitude: 45.0616,
    longitude: -93.5608,
  },
  // -----------------------------------------------------------------------
  // 63. InterVision Systems — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "InterVision Systems",
    website: "intervision.com",
    hqCity: "Santa Clara",
    hqState: "CA",
    annualRevenue: 500,
    profit: null,
    employeeCount: 700,
    ownershipType: "PE",
    strategicSpecialty: "AI & Cloud Managed Services",
    strategicFocus: "Cloud, managed services, AI, and cybersecurity solutions for enterprise clients",
    topVendors: ["Microsoft", "AWS", "Cisco", "Dell"],
    topCustomers: ["Enterprise", "Technology", "Healthcare"],
    yearFounded: 1993,
    description: "PE-backed IT solutions provider focused on cloud, managed services, AI, and cybersecurity. Based in Silicon Valley with a growing AI practice and national managed services footprint.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 16,
    ebitdaMargin: 13,
    customerSegment: "Enterprise",
    specialties: ["Cloud", "Managed Services", "AI", "Cybersecurity"],
    latitude: 37.3541,
    longitude: -121.9552,
  },
  // -----------------------------------------------------------------------
  // 64. TierPoint — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "TierPoint",
    website: "tierpoint.com",
    hqCity: "St. Louis",
    hqState: "MO",
    annualRevenue: 700,
    profit: null,
    employeeCount: 1000,
    ownershipType: "PE",
    strategicSpecialty: "Colocation & Managed Cloud",
    strategicFocus: "Cloud, colocation, managed services, and disaster recovery across a national data center footprint",
    topVendors: ["Dell", "VMware", "Microsoft", "Zerto"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Financial Services"],
    yearFounded: 2010,
    description: "PE-backed data center and cloud services provider operating 40+ data centers nationwide. Delivers colocation, managed cloud, disaster recovery, and security services to mid-market enterprises.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 8,
    ebitdaMargin: 20,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Colocation", "Managed Services", "Disaster Recovery"],
    latitude: 38.627,
    longitude: -90.1994,
  },
  // -----------------------------------------------------------------------
  // 65. VC3 — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "VC3",
    website: "vc3.com",
    hqCity: "Columbia",
    hqState: "SC",
    annualRevenue: 75,
    profit: null,
    employeeCount: 300,
    ownershipType: "PE",
    strategicSpecialty: "Government IT & MSP",
    strategicFocus: "Managed services, cybersecurity, cloud, and government IT solutions for municipalities and SMB",
    topVendors: ["Microsoft", "Dell", "Cisco", "Fortinet"],
    topCustomers: ["Municipalities", "Local Government", "SMB"],
    yearFounded: 1994,
    description: "PE-backed managed services provider specializing in local government and municipal IT. Delivers cybersecurity, cloud, and managed IT to cities, counties, and small businesses in the Southeast.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 20,
    ebitdaMargin: 18,
    customerSegment: "SMB",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Government IT"],
    latitude: 34.0007,
    longitude: -81.0348,
  },
  // -----------------------------------------------------------------------
  // 66. NetStandard — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "NetStandard",
    website: "netstandard.com",
    hqCity: "Kansas City",
    hqState: "MO",
    annualRevenue: 65,
    profit: null,
    employeeCount: 180,
    ownershipType: "PE",
    strategicSpecialty: "Managed Services & Compliance",
    strategicFocus: "Managed IT services, cloud, cybersecurity, and compliance solutions for mid-market enterprises",
    topVendors: ["Microsoft", "Dell", "Cisco", "SentinelOne"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Professional Services"],
    yearFounded: 2001,
    description: "PE-backed managed IT services provider in the Kansas City metro. Delivers managed services, cybersecurity, cloud, and compliance solutions with a focus on mid-market enterprises.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 17,
    ebitdaMargin: 14,
    customerSegment: "Mid-Market",
    specialties: ["Managed Services", "Cloud", "Cybersecurity", "Compliance"],
    latitude: 39.0997,
    longitude: -94.5786,
  },
  // -----------------------------------------------------------------------
  // 67. IT Solutions — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "IT Solutions",
    website: "itsolutions.com",
    hqCity: "Fort Lauderdale",
    hqState: "FL",
    annualRevenue: 130,
    profit: null,
    employeeCount: 220,
    ownershipType: "Private",
    strategicSpecialty: "Managed Services & VoIP",
    strategicFocus: "Managed IT services, cloud, cybersecurity, and VoIP communications for mid-market enterprises in South Florida",
    topVendors: ["Microsoft", "Dell", "Cisco", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Legal", "Healthcare"],
    yearFounded: 1998,
    description: "South Florida IT solutions provider offering managed services, cloud, cybersecurity, and VoIP. Focused on mid-market enterprises in the Fort Lauderdale and Miami metro areas.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 15,
    ebitdaMargin: 15,
    customerSegment: "Mid-Market",
    specialties: ["Managed Services", "Cloud", "Cybersecurity", "VoIP"],
    latitude: 26.1224,
    longitude: -80.1373,
  },
  // -----------------------------------------------------------------------
  // 68. Thrive — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Thrive",
    website: "thrive.com",
    hqCity: "Foxborough",
    hqState: "MA",
    annualRevenue: 300,
    profit: null,
    employeeCount: 700,
    ownershipType: "PE",
    strategicSpecialty: "NextGen Managed Services",
    strategicFocus: "Managed services, cybersecurity, cloud, and compliance solutions with aggressive PE-fueled growth",
    topVendors: ["Microsoft", "CrowdStrike", "Palo Alto", "Dell"],
    topCustomers: ["Mid-Market Enterprise", "Financial Services", "Healthcare"],
    yearFounded: 2001,
    description: "PE-backed managed services platform executing an aggressive buy-and-build strategy. Delivers cybersecurity, cloud, and compliance-ready managed IT services to mid-market enterprises.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.65,
    growthRate: 28,
    ebitdaMargin: 16,
    customerSegment: "Mid-Market",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Compliance"],
    latitude: 42.0654,
    longitude: -71.2478,
  },
  // -----------------------------------------------------------------------
  // 69. Resultant — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Resultant",
    website: "resultant.com",
    hqCity: "Indianapolis",
    hqState: "IN",
    annualRevenue: 180,
    profit: null,
    employeeCount: 400,
    ownershipType: "Private",
    strategicSpecialty: "Data Analytics & Consulting",
    strategicFocus: "Cloud, data analytics, cybersecurity, and IT consulting for mid-market and public sector",
    topVendors: ["Microsoft", "AWS", "Dell", "Tableau"],
    topCustomers: ["State Government", "Healthcare", "Education"],
    yearFounded: 2008,
    description: "Indianapolis-based technology consulting firm specializing in data analytics, cloud, cybersecurity, and digital transformation. Strong public sector practice with state government clients.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 20,
    ebitdaMargin: 15,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Data Analytics", "Cybersecurity", "Consulting"],
    latitude: 39.7684,
    longitude: -86.1581,
  },
  // -----------------------------------------------------------------------
  // 70. Cleareon — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Cleareon",
    website: "cleareon.com",
    hqCity: "Atlanta",
    hqState: "GA",
    annualRevenue: 90,
    profit: null,
    employeeCount: 150,
    ownershipType: "PE",
    strategicSpecialty: "SD-WAN & Networking",
    strategicFocus: "Cloud, managed services, networking, and SD-WAN solutions for mid-market enterprises in the Southeast",
    topVendors: ["Cisco", "Microsoft", "Dell", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Multi-Location Businesses", "Retail"],
    yearFounded: 2010,
    description: "PE-backed managed network services provider based in Atlanta. Specializes in SD-WAN, cloud connectivity, and managed networking for mid-market enterprises with distributed locations.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 19,
    ebitdaMargin: 17,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Managed Services", "Networking", "SD-WAN"],
    latitude: 33.749,
    longitude: -84.388,
  },
  // -----------------------------------------------------------------------
  // 71. Xantrion — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Xantrion",
    website: "xantrion.com",
    hqCity: "Oakland",
    hqState: "CA",
    annualRevenue: 40,
    profit: null,
    employeeCount: 85,
    ownershipType: "Private",
    strategicSpecialty: "SMB Managed Services",
    strategicFocus: "Managed IT services, cybersecurity, cloud, and help desk for small and mid-sized businesses in the Bay Area",
    topVendors: ["Microsoft", "Dell", "SentinelOne", "Datto"],
    topCustomers: ["SMB", "Nonprofits", "Professional Services"],
    yearFounded: 1988,
    description: "Bay Area managed IT services provider serving small and mid-sized businesses. Delivers cybersecurity, cloud, and help desk support with a consultative, long-term partner approach.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.55,
    growthRate: 15,
    ebitdaMargin: 20,
    customerSegment: "SMB",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Help Desk"],
    latitude: 37.8044,
    longitude: -122.2712,
  },
  // -----------------------------------------------------------------------
  // 72. Sourcepass — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Sourcepass",
    website: "sourcepass.com",
    hqCity: "New York",
    hqState: "NY",
    annualRevenue: 55,
    profit: null,
    employeeCount: 250,
    ownershipType: "PE",
    strategicSpecialty: "MSP Rollup Platform",
    strategicFocus: "Managed services, cybersecurity, cloud, and VoIP through PE-backed buy-and-build MSP aggregation",
    topVendors: ["Microsoft", "Dell", "Cisco", "Fortinet"],
    topCustomers: ["SMB", "Professional Services", "Financial Services"],
    yearFounded: 2019,
    description: "PE-backed MSP aggregation platform executing rapid buy-and-build strategy. Acquires regional MSPs and unifies them under a single brand for managed services, cybersecurity, and cloud.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 40,
    ebitdaMargin: 12,
    customerSegment: "SMB",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "VoIP"],
    latitude: 40.7128,
    longitude: -74.006,
  },
  // -----------------------------------------------------------------------
  // 73. CentraComm — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "CentraComm",
    website: "centracomm.com",
    hqCity: "Charlotte",
    hqState: "NC",
    annualRevenue: 60,
    profit: null,
    employeeCount: 100,
    ownershipType: "Private",
    strategicSpecialty: "Cloud & Networking",
    strategicFocus: "Cloud, managed services, cybersecurity, and networking for mid-market enterprises in the Carolinas",
    topVendors: ["Cisco", "Dell", "Microsoft", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Manufacturing"],
    yearFounded: 2005,
    description: "Charlotte-based IT solutions provider offering cloud, managed services, cybersecurity, and networking. Focused on mid-market enterprises in the Carolinas region.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.55,
    growthRate: 16,
    ebitdaMargin: 14,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Managed Services", "Cybersecurity", "Networking"],
    latitude: 35.2271,
    longitude: -80.8431,
  },
  // -----------------------------------------------------------------------
  // 74. TekLinks — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "TekLinks",
    website: "teklinks.com",
    hqCity: "Birmingham",
    hqState: "AL",
    annualRevenue: 95,
    profit: null,
    employeeCount: 200,
    ownershipType: "PE",
    strategicSpecialty: "Cloud & Data Center",
    strategicFocus: "Cloud, managed services, cybersecurity, and data center solutions for mid-market in the Southeast",
    topVendors: ["Dell", "Microsoft", "Cisco", "VMware"],
    topCustomers: ["Mid-Market Enterprise", "Healthcare", "Manufacturing"],
    yearFounded: 1997,
    description: "PE-backed IT solutions provider based in Birmingham, Alabama. Delivers cloud, managed services, cybersecurity, and data center solutions to mid-market enterprises in the Deep South.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 11,
    ebitdaMargin: 13,
    customerSegment: "Mid-Market",
    specialties: ["Cloud", "Managed Services", "Cybersecurity", "Data Center"],
    latitude: 33.5207,
    longitude: -86.8025,
  },
  // -----------------------------------------------------------------------
  // 75. Cerdant — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Cerdant",
    website: "cerdant.com",
    hqCity: "Richmond",
    hqState: "VA",
    annualRevenue: 50,
    profit: null,
    employeeCount: 80,
    ownershipType: "Private",
    strategicSpecialty: "Cybersecurity & Compliance",
    strategicFocus: "Cybersecurity, cloud, managed services, and compliance solutions for mid-market enterprises",
    topVendors: ["Microsoft", "CrowdStrike", "Cisco", "Fortinet"],
    topCustomers: ["Mid-Market Enterprise", "Government", "Healthcare"],
    yearFounded: 2009,
    description: "Richmond-based cybersecurity and managed services provider. Delivers compliance-focused security, cloud, and managed IT solutions to mid-market enterprises in Virginia and the Mid-Atlantic.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.55,
    growthRate: 22,
    ebitdaMargin: 18,
    customerSegment: "Mid-Market",
    specialties: ["Cybersecurity", "Cloud", "Managed Services", "Compliance"],
    latitude: 37.5407,
    longitude: -77.436,
  },
  // -----------------------------------------------------------------------
  // 76. Ntiva — Source 2 only
  // -----------------------------------------------------------------------
  {
    name: "Ntiva",
    website: "ntiva.com",
    hqCity: "McLean",
    hqState: "VA",
    annualRevenue: 110,
    profit: null,
    employeeCount: 400,
    ownershipType: "PE",
    strategicSpecialty: "SMB Managed Services",
    strategicFocus: "Managed IT services, cybersecurity, cloud, and help desk support for small and mid-sized businesses",
    topVendors: ["Microsoft", "Dell", "Cisco", "Datto"],
    topCustomers: ["SMB", "Professional Services", "Nonprofits"],
    yearFounded: 2004,
    description: "PE-backed managed IT services provider serving small and mid-sized businesses in the DC metro area. Delivers cybersecurity, cloud, and help desk services with a consultative approach.",
    dataSources: ["ma-engine"],
    confidenceScore: 0.6,
    growthRate: 22,
    ebitdaMargin: 15,
    customerSegment: "SMB",
    specialties: ["Managed Services", "Cybersecurity", "Cloud", "Help Desk"],
    latitude: 38.9339,
    longitude: -77.1773,
  },
] as const

// ============================================================================
// Seed Function
// ============================================================================

async function main() {
  if (!db) {
    console.error('DATABASE_URL environment variable is required')
    process.exit(1)
  }

  console.log(`Seeding ${UNIFIED_VARS.length} unified VARs...`)

  // Truncate existing data
  await db.delete(vars)
  console.log('Cleared existing vars table')

  // Insert each VAR individually to avoid payload size issues
  let inserted = 0
  for (const v of UNIFIED_VARS) {
    await db.insert(vars).values({
      name: v.name,
      website: v.website,
      hqCity: v.hqCity,
      hqState: v.hqState,
      annualRevenue: v.annualRevenue,
      profit: v.profit,
      employeeCount: v.employeeCount,
      ownershipType: v.ownershipType,
      strategicSpecialty: v.strategicSpecialty,
      strategicFocus: v.strategicFocus,
      topVendors: v.topVendors as string[],
      topCustomers: v.topCustomers as string[],
      yearFounded: v.yearFounded,
      description: v.description,
      dataSources: v.dataSources as string[],
      confidenceScore: v.confidenceScore,
      growthRate: v.growthRate,
      ebitdaMargin: v.ebitdaMargin,
      customerSegment: v.customerSegment,
      specialties: v.specialties as string[] | null,
      latitude: v.latitude,
      longitude: v.longitude,
      discoveredBy: 'seed',
    })
    inserted++
    if (inserted % 10 === 0) {
      console.log(`  ...inserted ${inserted}/${UNIFIED_VARS.length}`)
    }
  }

  console.log(`Seeded ${inserted} unified VARs successfully`)
  console.log(`  - Source 1 only (VAR Directory): 32 companies`)
  console.log(`  - Merged (both sources): 19 companies`)
  console.log(`  - Source 2 only (M&A Engine): 25 companies`)
  console.log(`  Total: ${UNIFIED_VARS.length} companies`)
}

main().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
